language: python
python:
  - '3.9'
sudo: required
install:
  - python3 -m venv env
  - source env/bin/activate
  - python3 -m pip install -r requirements.txt
script:
  # Staring streamlit in the background:
  - nohup streamlit run app.py &

  # Checking if streamlit is running:
  - if [[ ! $(ps aux | grep streamlit | grep -v grep) ]]; then 
      echo "Launcing streamlit server failed."; 
      cat nohup.out; 
      exit 1; 
    else 
      echo "Streamlit server running"
    fi
