metric_calculation:
  # Specifies the upcoming Open Targets release for which the metrics are being computed.
  # See documentation (`metric-calculation.md`) about how to set it in various cases.
  ot_release: ???

  data_repositories:
    release_bucket: gs://open-targets-pre-data-releases
    metrics_root: gs://otar000-evidence_input/release-metrics

  datasets:
    evidence_post_etl: output/evidence_*
    evidence_failed: excluded/evidence
    associations_overall_indirect: output/association_overall_indirect
    associations_overall_direct: output/association_overall_direct
    associations_source_indirect: output/association_by_datasource_indirect
    associations_source_direct: output/association_by_datasource_direct
    diseases: output/disease
    targets: output/target
    drugs: output/drug_molecule

  gold_standard:
    associations: ${metric_calculation.data_repositories.metrics_root}/gold-standard/informa_abbvie.tsv
    efo_mappings: ${metric_calculation.data_repositories.metrics_root}/gold-standard/mesh_mappings.tsv

  outputs:
    hf_repo_id: opentargets/ot-release-metrics
    release_output_path: ${metric_calculation.data_repositories.release_bucket}/${metric_calculation.ot_release}/metrics.csv

