metric_calculation:
  # Specifies the upcoming Open Targets release for which the metrics are being computed.
  # See documentation (`metric-calculation.md`) about how to set it in various cases.
  ot_release: ???

  data_repositories:
    release_output_root: gs://open-targets-pre-data-releases/${metric_calculation.ot_release}/output
    metadata_output_root: gs://open-targets-pre-data-releases/${metric_calculation.ot_release}/metadata
    metrics_root: gs://otar000-evidence_input/release-metrics

  datasets:
    # Post ETL data.
    evidence: ${metric_calculation.data_repositories.release_output_root}/evidence
    evidence_failed: gs://open-targets-pre-data-releases/${metric_calculation.ot_release}/excluded/evidence
    associations_overall_indirect: ${metric_calculation.data_repositories.release_output_root}/association_by_overall_indirect
    associations_overall_direct: ${metric_calculation.data_repositories.release_output_root}/association_overall_direct
    associations_source_indirect: ${metric_calculation.data_repositories.release_output_root}/association_by_datasource_indirect
    associations_source_direct: ${metric_calculation.data_repositories.release_output_root}/association_by_datasource_direct
    diseases: ${metric_calculation.data_repositories.release_output_root}/disease
    targets: ${metric_calculation.data_repositories.release_output_root}/target
    drugs: ${metric_calculation.data_repositories.release_output_root}/drug_molecule

  metadata:
    evidence: ${metric_calculation.data_repositories.metadata_output_root}/evidence

  gold_standard:
    associations: ${metric_calculation.data_repositories.metrics_root}/gold-standard/informa_abbvie.tsv
    efo_mappings: ${metric_calculation.data_repositories.metrics_root}/gold-standard/mesh_mappings.tsv

  outputs:
    hf_repo_id: opentargets/ot-release-metrics
    release_output_path: gs://open-targets-pre-data-releases/${metric_calculation.ot_release}/metrics.csv

metric_visualization:
  parameters:
    yellow_highlight_bound: 0.2
    red_highlight_bound: 0.5
