metric_calculation:
  # Specifies the upcoming Open Targets release for which the metrics are being computed, for example "23.12".
  # If computing metrics in pre-ETL mode, append "_pre", for example "23.12_pre".
  ot_release: ???

  data_repositories:
    release_output_root: gs://open-targets-pre-data-releases/${metric_calculation.ot_release}/output/etl/parquet
    metrics_root: gs://otar000-evidence_input/release-metrics

  datasets:
    # Post ETL data.
    evidence: ${metric_calculation.data_repositories.release_output_root}/evidence
    evidence_failed: ${metric_calculation.data_repositories.release_output_root}/errors/evidence
    associations_overall_indirect: ${metric_calculation.data_repositories.release_output_root}/associationByOverallIndirect
    associations_overall_direct: ${metric_calculation.data_repositories.release_output_root}/associationByOverallDirect
    associations_source_indirect: ${metric_calculation.data_repositories.release_output_root}/associationByDatasourceIndirect
    associations_source_direct: ${metric_calculation.data_repositories.release_output_root}/associationByDatasourceDirect
    diseases: ${metric_calculation.data_repositories.release_output_root}/diseases
    targets: ${metric_calculation.data_repositories.release_output_root}/targets
    drugs: ${metric_calculation.data_repositories.release_output_root}/molecule

  gold_standard:
    associations: ${metric_calculation.data_repositories.metrics_root}/gold-standard/informa_abbvie.tsv
    efo_mappings: ${metric_calculation.data_repositories.metrics_root}/gold-standard/mesh_mappings.tsv

  outputs:
    # Metrics are written to the directory that contains them all.
    all_metrics_path_base: ${metric_calculation.data_repositories.metrics_root}
    release_output_path: ${metric_calculation.data_repositories.release_output_root}/metadata/metrics/${metric_calculation.ot_release}.csv

metric_visualization:
  parameters:
    yellow_highlight_bound: 0.2
    red_highlight_bound: 0.5
